# Generated by Django 5.1.7 on 2025-03-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='contactno',
            new_name='f',
        ),
        migrations.AlterField(
            model_name='member',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
