# Generated by Django 5.1.7 on 2025-03-15 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_contactno_member_f_alter_member_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='f',
            new_name='contactno',
        ),
    ]
