# Generated by Django 5.1.7 on 2025-03-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_f_member_contactno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='datetime',
        ),
        migrations.AddField(
            model_name='member',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='member',
            name='intime',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='member',
            name='outtime',
            field=models.TimeField(default='17:00:00'),
        ),
    ]
