# Generated by Django 5.1.7 on 2025-03-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user_conformpassword_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='salary',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
    ]
