# Generated by Django 5.1.7 on 2025-03-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_member_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='empid',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='empname',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default=False, upload_to='picture/'),
        ),
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
