# Generated by Django 5.1.7 on 2025-03-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_user_age_user_date_user_department_user_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='empemail',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
