# Generated by Django 5.1.7 on 2025-03-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_user_empemail_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default=False, upload_to='pictures/'),
        ),
    ]
