# Generated by Django 5.1.7 on 2025-03-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_user_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='empid',
            new_name='employeeid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='empname',
            new_name='employeename',
        ),
        migrations.RemoveField(
            model_name='user',
            name='empemail',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
