# Generated by Django 5.1.7 on 2025-03-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_empid_user_employeeid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employeeemail',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
