# Generated by Django 5.1.7 on 2025-03-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_user_age_remove_user_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeename', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('employeeid', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=15)),
                ('date', models.DateField(auto_now=True)),
                ('gender', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=15)),
                ('employeeemail', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=10)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/')),
            ],
        ),
    ]
