# Generated by Django 5.1.7 on 2025-03-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_employee_employeeemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='intime',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='employee',
            name='outtime',
            field=models.TimeField(default='17:00:00'),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
