# Generated by Django 5.1.7 on 2025-03-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_employee_intime_employee_outtime_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='indate',
            field=models.DateField(auto_now=True),
        ),
    ]
