# Generated by Django 5.1.7 on 2025-03-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_employee_indate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='accountnumber',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='bankbranch',
            field=models.CharField(default=False, max_length=40),
        ),
        migrations.AddField(
            model_name='employee',
            name='bankcode',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='bankname',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='branchaddress',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(default=False, max_length=35),
        ),
        migrations.AddField(
            model_name='employee',
            name='country',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeetype',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='enddate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='fathercontact',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='fathername',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='mothername',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='requestday',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='shifttime',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='startdate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='state',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='workdepartment',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
