# Generated by Django 5.1.7 on 2025-03-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_employee_accountnumber_employee_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fathername',
            field=models.CharField(default=False, max_length=30, null=True),
        ),
    ]
