# Generated by Django 5.1.7 on 2025-03-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_employee_intime_alter_employee_outtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
