# Generated by Django 5.1.7 on 2025-03-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_employee_age_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeename', models.CharField(max_length=100)),
                ('employeeid', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('indate', models.DateField(auto_now=True)),
                ('intime', models.TimeField(default='09:00:00', null=True)),
                ('outtime', models.TimeField(default='17:00:00', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeename', models.CharField(max_length=100)),
                ('employeeid', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100, null=True)),
                ('startdate', models.DateField(auto_now=True)),
                ('enddate', models.DateField(auto_now=True)),
                ('requestday', models.CharField(default=False, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeename', models.CharField(max_length=100)),
                ('employeeid', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100, null=True)),
                ('bankname', models.CharField(default=False, max_length=30, null=True)),
                ('bankbranch', models.CharField(default=False, max_length=40, null=True)),
                ('accountnumber', models.CharField(default=False, max_length=30, null=True)),
                ('bankcode', models.CharField(default=False, max_length=20, null=True)),
                ('branchaddress', models.CharField(default=False, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathername', models.CharField(default=False, max_length=30, null=True)),
                ('mothername', models.CharField(default=False, max_length=30, null=True)),
                ('fathercontact', models.CharField(default=False, max_length=30, null=True)),
                ('address', models.CharField(default=False, max_length=50, null=True)),
                ('city', models.CharField(default=False, max_length=35, null=True)),
                ('state', models.CharField(default=False, max_length=30, null=True)),
                ('country', models.CharField(default=False, max_length=30, null=True)),
                ('status', models.CharField(default=False, max_length=20, null=True)),
                ('workdepartment', models.CharField(default=False, max_length=30, null=True)),
                ('shifttime', models.CharField(default=False, max_length=30, null=True)),
                ('employeetype', models.CharField(default=False, max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='accountnumber',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bankbranch',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bankcode',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bankname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='branchaddress',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='country',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employeetype',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='fathercontact',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='fathername',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='indate',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='intime',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mothername',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='outtime',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='requestday',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='shifttime',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='startdate',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='state',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='workdepartment',
        ),
    ]
