# Generated by Django 5.1.7 on 2025-03-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_attendance_leave_payroll_personal_delete_member_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personal',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employeeemail',
            new_name='gmail',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='education',
            new_name='qualification',
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(default=False, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='country',
            field=models.CharField(default=False, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeetype',
            field=models.CharField(default=False, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='experience',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='fathercontact',
            field=models.CharField(default=False, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='fathername',
            field=models.CharField(default=False, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='joindate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='mothername',
            field=models.CharField(default=False, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='shifttime',
            field=models.CharField(default=False, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='state',
            field=models.CharField(default=False, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(default=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='workdepartment',
            field=models.CharField(default=False, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='worklocation',
            field=models.CharField(default=False, max_length=30, null=True),
        ),
    ]
