# Generated by Django 5.1.7 on 2025-03-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_delete_personal_rename_employeeemail_employee_gmail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeename', models.CharField(max_length=100)),
                ('assets', models.CharField(max_length=30)),
                ('assetname', models.CharField(max_length=30)),
                ('assigndate', models.DateField(auto_now=True)),
                ('batchno', models.CharField(max_length=30)),
                ('assignby', models.CharField(max_length=30)),
            ],
        ),
    ]
