# Generated by Django 5.1.7 on 2025-03-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tenth_certificate', models.FileField(blank=True, null=True, upload_to='documents/tenth/')),
                ('twelth_certificate', models.FileField(blank=True, null=True, upload_to='documents/twelfth/')),
                ('graduate_certificate', models.FileField(blank=True, null=True, upload_to='documents/graduate/')),
                ('professional_certificate', models.FileField(blank=True, null=True, upload_to='documents/professional/')),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to='documents/aadhar/')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='documents/pan/')),
                ('passport', models.FileField(blank=True, null=True, upload_to='documents/passport/')),
                ('driving_license', models.FileField(blank=True, null=True, upload_to='documents/driving_license/')),
                ('medical_certificate', models.FileField(blank=True, null=True, upload_to='documents/medical/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
