# Generated by Django 5.1.7 on 2025-03-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_documentupload_driving_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentupload',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
