# Generated by Django 5.1.7 on 2025-03-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_documentupload_aadhar_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='code',
            field=models.CharField(default=False, max_length=30, null=True),
        ),
    ]
