# Generated by Django 5.1.7 on 2025-03-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_payroll_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentupload',
            old_name='name',
            new_name='Employeename',
        ),
    ]
