# Generated by Django 5.1.7 on 2025-03-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_useradmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradmin',
            name='conformpassword',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
