# Generated by Django 5.1.7 on 2025-03-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_useradmin_conformpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Not Informed', 'Not Informed')], default='Not Informed', max_length=20),
        ),
    ]
