# Generated by Django 5.1.7 on 2025-03-31 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_leave_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentupload',
            old_name='Employeename',
            new_name='employeename',
        ),
    ]
