# Generated by Django 5.1.7 on 2025-04-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_payroll_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeename', models.CharField(max_length=255)),
                ('employeeid', models.CharField(max_length=30)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('gmail', models.CharField(max_length=40, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('leavedate', models.DateField(auto_now=True)),
                ('reason', models.CharField(max_length=50)),
            ],
        ),
    ]
