# Generated by Django 5.1.7 on 2025-04-01 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_remove_resign_description_resign_resignletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resign',
            old_name='resignletter',
            new_name='resignationletter',
        ),
    ]
