# Generated by Django 5.1.7 on 2025-04-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_rename_resignletter_resign_resignationletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resign',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
