# Generated by Django 5.1.7 on 2025-04-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_alter_resign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resign',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=20, null=True),
        ),
    ]
