# Generated by Django 5.1.7 on 2025-04-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_alter_resign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
