# Generated by Django 5.1.7 on 2025-04-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_asset_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
