# Generated by Django 5.1.7 on 2025-04-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_alter_employee_date_alter_employee_joindate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='accountnumber',
            field=models.CharField(default=False, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='code',
            field=models.CharField(default=False, max_length=12, null=True),
        ),
    ]
