# Generated by Django 5.1.7 on 2025-04-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_alter_payroll_accountnumber_alter_payroll_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('gmail', models.EmailField(max_length=255)),
                ('jobrole', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=255)),
                ('mobilenumber', models.CharField(max_length=20)),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
