# Generated by Django 5.1.7 on 2025-04-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
