# Generated by Django 5.1.7 on 2025-04-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_career_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=20, null=True),
        ),
    ]
